server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        secure: true

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # Production: Connection pooling (HikariCP is default)
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: game_timer
        # Production: Disable SQL logging
        show_sql: false
        format_sql: false

  flyway:
    locations: classpath:db/migration/postgres

# Production: Conservative logging
logging:
  level:
    se.bytebrew.auth_server: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.flywaydb: INFO

  # Production: Log to file for Coolify to collect
  file:
    name: ${LOG_FILE:/app/logs/boys-service.log}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
