auth-server:
  base-url: ${AUTH_SERVER_BASE_URL:http://auth-server.local:8081}

web:
  base-url: ${WEB_BASE_URL:http://localhost:4200}

app:
  base-url: ${APP_BASE_URL:http://service-provider.local:8080}

server:
  port: 8080

spring:
  application:
    name: boys-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${auth-server.base-url}/oauth2/jwks
      client:
        registration:
          auth-server:
            client-id: ${CLIENT_ID:1234}
            client-secret: ${CLIENT_SECRET:4321}
            authorization-grant-type: authorization_code
            redirect-uri: ${app.base-url}/login/oauth2/code/auth-server
        provider:
          auth-server:
            authorization-uri: ${auth-server.base-url}/oauth2/authorize
            token-uri: ${auth-server.base-url}/oauth2/token
            user-info-uri: ${auth-server.base-url}/userinfo
            user-name-attribute: username
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: boys
    default-schema: boys

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:${web.base-url}}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
